/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTSA.view;
import UTSA.controller.*;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author ACER
 */
public class FormPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form FormPelanggan
     */
    PelangganController controller;
    public FormPelanggan() {
        initComponents();
        controller = new PelangganController(this);
        controller.bersihForm();
        controller.tampil();
    }
    public javax.swing.JTextField getTxtKodePelanggan(){
        return txtKodePelanggan;
    }
    
    public javax.swing.JTextField getTxtNama(){
        return txtNama;
    }
    
    public javax.swing.JTextField getTxtMeterBulanIni(){
        return txtMeterBulanIni;
    }
    
    public javax.swing.JTextField getTxtMeterBulanLalu(){
        return txtMeterBulanLalu;
    }
    public javax.swing.JTextField getTxtTarif(){
        return txtTarif;
    }
    public javax.swing.JTextField getTxtDiskon(){
        return txtDiskon;
    }
    
    
    public javax.swing.JTable getTblPelanggan(){
        return tblPelanggan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodePelanggan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtMeterBulanIni = new javax.swing.JTextField();
        txtMeterBulanLalu = new javax.swing.JTextField();
        txtTarif = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Pelanggan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 130, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 110, 20);

        jLabel3.setText("Meter Bulan Ini");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 110, 16);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 37, 0);

        jLabel5.setText("Meter Bulan Lalu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 100, 16);

        jLabel6.setText("Tarif");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 70, 16);

        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 36, 16);

        txtKodePelanggan.setText("jTextField1");
        getContentPane().add(txtKodePelanggan);
        txtKodePelanggan.setBounds(200, 50, 530, 30);

        txtNama.setText("jTextField2");
        getContentPane().add(txtNama);
        txtNama.setBounds(200, 80, 530, 30);

        txtMeterBulanIni.setText("jTextField3");
        getContentPane().add(txtMeterBulanIni);
        txtMeterBulanIni.setBounds(200, 112, 530, 30);

        txtMeterBulanLalu.setText("jTextField4");
        getContentPane().add(txtMeterBulanLalu);
        txtMeterBulanLalu.setBounds(200, 142, 530, 30);

        txtTarif.setText("jTextField5");
        getContentPane().add(txtTarif);
        txtTarif.setBounds(200, 170, 530, 30);

        txtDiskon.setText("jTextField6");
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(200, 202, 530, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(130, 280, 72, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(360, 280, 72, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(610, 280, 72, 23);

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "MBI", "MBL", "Tarif", "Diskon", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPelanggan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 320, 770, 280);

        setSize(new java.awt.Dimension(851, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.savePelanggan();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.updatePelanggan();
        controller.tampil();
        controller.bersihForm();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        // TODO add your handling code here:
        controller.getPelanggan ();
    }//GEN-LAST:event_tblPelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtKodePelanggan;
    private javax.swing.JTextField txtMeterBulanIni;
    private javax.swing.JTextField txtMeterBulanLalu;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables
}
