/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aura270423.view;
import aura270423.controller.PengembalianController;
import javax.swing.*;
/**
 *
 * @author ACER
 */
public class FormPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form FormPengembalian
     */
    PengembalianController controller;
    public FormPengembalian() {
        initComponents();
        controller = new PengembalianController(this);
        controller.clearForm();
        controller.tampilDataPeminjaman();
        controller.getTglSekarang();
    }
    
    public JTextField getTxtNobp(){
        return txtNobp;
    }
    
    public JTextField getTxtNama(){
        return txtNama;
    }
    
    public JTextField getTxtTglKembali(){
        return txtTglKembali;
    }
    
    public JTextField getTxtTglDikembalikan(){
        return txtTglDikembalikan;
    }
    
    public JTextField getTxtTerlambat(){
        return txtTerlambat;
    }
    
    public JTextField getTxtDenda(){
        return txtDenda;
    }
    
    public javax.swing.JTable getTblPeminjaman(){
        return tblPeminjaman;
    }
    
    public javax.swing.JTable getTblPengembalian(){
        return tblPengembalian;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();
        txtNobp = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTglKembali = new javax.swing.JTextField();
        txtTglDikembalikan = new javax.swing.JTextField();
        txtTerlambat = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPengembalian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nobp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 89, 25);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 80, 20);

        jLabel3.setText("Tgl Kembali");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 90, 20);

        jLabel4.setText("Tgl Pengembalian");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 120, 30);

        jLabel5.setText("Terlambat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 110, 30);

        jLabel6.setText("Denda");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 190, 80, 30);

        jButton1.setText("Kembalikan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 250, 92, 23);

        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOBP", "Nama", "Tgl Pinjam", "Tgl Kembali"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeminjaman);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 40, 380, 200);

        txtNobp.setText("jTextField1");
        getContentPane().add(txtNobp);
        txtNobp.setBounds(130, 40, 200, 30);

        txtNama.setText("jTextField2");
        txtNama.setName(""); // NOI18N
        getContentPane().add(txtNama);
        txtNama.setBounds(130, 70, 200, 30);

        txtTglKembali.setText("jTextField3");
        getContentPane().add(txtTglKembali);
        txtTglKembali.setBounds(130, 100, 200, 30);

        txtTglDikembalikan.setText("jTextField4");
        getContentPane().add(txtTglDikembalikan);
        txtTglDikembalikan.setBounds(130, 130, 200, 30);

        txtTerlambat.setText("jTextField5");
        getContentPane().add(txtTerlambat);
        txtTerlambat.setBounds(130, 160, 200, 30);

        txtDenda.setText("jTextField6");
        getContentPane().add(txtDenda);
        txtDenda.setBounds(130, 190, 200, 30);

        tblPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOBP", "Nama", "Kode Buku", "Tgl Pinjam", "Tgl Kembali", "Tgl Dikembalikan", "Terlambat", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPengembalian);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 290, 700, 280);

        setSize(new java.awt.Dimension(754, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.savePengembalian();
//        controller.tampil();
//        controller.bersihForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeminjamanMouseClicked
        // TODO add your handling code here:
        controller.getPeminjaman();
        controller.hitungDenda();
    }//GEN-LAST:event_tblPeminjamanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTable tblPengembalian;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNobp;
    private javax.swing.JTextField txtTerlambat;
    private javax.swing.JTextField txtTglDikembalikan;
    private javax.swing.JTextField txtTglKembali;
    // End of variables declaration//GEN-END:variables
}
